### ISSUE TITLE
Get rid of giella-lib and associated downloads

### ISSUE THREAD

**Issue by flammie** [giellalt/giella-core#1]
On my mac it tries to connect to https://5 so probably some stray version number in rsync stuff?

**Comment by snomos** [comment]
`giella-libs` contains old prebuilt binaries for LO-oxt files and some other variants, and should really be abandoned as soon as all target platforms and host apps are covered by the CI & CD system (ie via páhkat etc). That is, the task is really to get rid of the giella-libs dependency completely.

**Comment by snomos** [comment]
The `connect to https://5` thing has now been solved. And I have removed old MacVoikko and MozVoikko targets from the build. What is left for now are the LO oxt builds. They should now build without errors in all cases as long as there is an internet connection.

**Comment by snomos** [comment]
We now have a new OXT for LO (Win and Mac) that picks up the spellers from Divvun Manager installations. We still would need something similar for Linux. After that we can kill giella-lib altogether.
