### ISSUE TITLE
make in docs fails in making targets (very many)

### ISSUE THREAD

**Issue by Trondtr** [giellalt/giella-core#10]
To repeat: Go to lang-nob/docs and write `make`

Result:

make[1]: *** No rule to make target `adverbs-stems.md'.  Stop.
make[1]: *** No rule to make target `nynorsk-stems-stems.md'.  Stop.
make[1]: *** No rule to make target `interjections-stems.md'.  Stop.
make[1]: *** No rule to make target `conjunctions-stems.md'.  Stop.
make[1]: *** No rule to make target `nouns-stems.md'.  Stop.
make[1]: *** No rule to make target `adjectives-stems.md'.  Stop.
make[1]: *** No rule to make target `nob-abbreviations-stems.md'.  Stop.
make[1]: *** No rule to make target `verbs-stems.md'.  Stop.
make[1]: *** No rule to make target `prepositions-stems.md'.  Stop.
make[1]: *** No rule to make target `subjunctions-stems.md'.  Stop.
make[1]: *** No rule to make target `pronouns-stems.md'.  Stop.
make[1]: *** No rule to make target `numerals-stems.md'.  Stop.
make[1]: *** No rule to make target `nob-propernouns-stems.md'.  Stop.
make[1]: `root-morphology.md' is up to date.
make[1]: *** No rule to make target `symbols-affixes.md'.  Stop.
make[1]: *** No rule to make target `nouns-affixes.md'.  Stop.
make[1]: *** No rule to make target `adjectives-affixes.md'.  Stop.
make[1]: *** No rule to make target `verbs-affixes.md'.  Stop.
make[1]: *** No rule to make target `abbreviations-affixes.md'.  Stop.
make[1]: *** No rule to make target `numerals-affixes.md'.  Stop.
make[1]: *** No rule to make target `propernouns-affixes.md'.  Stop.
make[1]: `phonology-morphology.md' is up to date.
make[1]: *** No rule to make target `compounding-morphology.md'.  Stop.
make[1]: *** No rule to make target `smi-propernouns-generated.md'.  Stop.
make[1]: *** No rule to make target `smi-acronyms-generated.md'.  Stop.
make[1]: *** No rule to make target `punctuation-generated.md'.  Stop.
make[1]: *** No rule to make target `symbols-generated.md'.  Stop.
make[1]: *** No rule to make target `arabic_roman_digits-generated.md'.  Stop.
make[1]: *** No rule to make target `smi-nob-abbreviations-generated.md'.  Stop.
make[1]: *** No rule to make target `smi-nob-propernouns-generated.md'.  Stop.
make[1]: *** No rule to make target `smi-abbreviations-generated.md'.  Stop.
make[1]: *** No rule to make target `transcriptor-abbrevs2text.md'.  Stop.

**Comment by flammie** [comment]
I removed all the targets from nob's docs Makefile earlied today, have you aupdated? it may need to clean `rm docs/generated* ` once...

**Comment by flammie** [comment]
also: https://github.com/giellalt/lang-nob/commit/bc6059d1ed322fde8142f934eb4a15ef6a2a336c

**Comment by flammie** [comment]
should be clear with recent templates and generated file cleanups
