### ISSUE TITLE
Split giella-shared in several repos

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#20]
# Background

`giella-shared` contains today a mixture of data for many different languages:

```
giella-shared/
├── all_langs
│   └── src
│       ├── filters ⇒ obligatory, move to giella-core?
│       └── fst ⇒ url, punctuation, symbols
├── eng ⇒ names for languages in English majority countries
├── smi ⇒ names, cg functions and dependency graphs mainly for Sámi languages
└── urj-Cyrl ⇒ names for Uralic languages written in Cyrillic
```

# Core idea

Ideally we would only have `giella-core` as a required dependency (thus needing to move the filters there), and everything else as separate repositories that can be subscribed on an as-needed/wanted basis.

By generalising sharing resources, it would also be straightforward to share content across language repositories, like including `sma` and `sme` proper nouns in `smj` (with some filtering and restrictions). Technically there would be no difference between getting content from `lang-sme` and `shared-smi`.

# Naming

- using a prefix `shared-`, parallel to `lang-`, `keyboard-` etc. It does not have to be what is suggested here, other suggestions are welcome.
- followed by a BCP 47 like locale tag, but also allowing language family tags such as `smi` and `urj`

# Concrete example

The present `giella-shared` would after a split become (with check marks for the actual split):

- [x] `shared-smi`: the present shared Sámi resources
- [x] `shared-mul`: the present shared symbols, url's and punctuation lexicons (`mul` = multiple languages)
- [x] `shared-eng`: present shared English resources (like names)
- [x] `shared-urj-Cyrl`: shared resources for Uralic languages written in Cyrillic
- [x] `giella-core/fst-filters/`: fst filters moved here, since they are a prerequisite for compiling fst's

Another example:

- using `lang-sme` as a source for North Sámi names when used in another Sámi language, like place names. Non-Sámi names in `lang-sme` would be filtered out, and generic last elements could be (automatically) adapted to Lule Sámi spelling and inflection as needed. This is relevant both for text analysis and parsing in general, but especially for TTS, where there is a need to get a best possible transcription and pronunciation of whatever is thrown at the system. Place names from related neightbouring languages will certainly be a pain point for many minority languages in such a context.

By treating all repos the same as a potential source for lexical and other resources, we get a more flexible and powerful infrastructure.

# Restrictions

Ideally the shared resources should never be required — without access to them the result should only be a smaller analyser with worse coverage. This will make `giella-core` the only required external dependency.

As far as possible, the resources in each repo should be independently compilable and testable, kind of like independent code libraries.

# Benefits

- more flexibility
- only use what is needed for a language, and start small and simple
- still access to all sorts of premade resources for various purposes
- easier version tagging of each shared resource
- with each repo containing a more clearly defined and limited set of data, it is easier to document, specify and reuse

# Considerations

## versioning

- should one always asume latest code
- or should it be possible to peg the inclusion to a specific version

## dependency management

We need a straightforward and simple system to declare dependency on a list of other repositories, kind of like Rust cargo lists. But as noted above, the system should be robust enough to not break if a resource is not available, only give a warning.

## CI

Dependency management needs to be automatic, at least for CI systems. We need at least:

- [x] simple dependency specification \\
    Covered by what is specified in `configure.ac`, at least for now
- [x] add routines to make sure that the dependencies are available in the following cases:
    - [x] when starting work (ie by running `./autogen.sh` in a directory, using the same cloning scheme as the depending repo — svn, git-ssh or git-https)
    - [x] during CI (Taskcluster, GH Actions, Tino's build machine)

# Cleanup

- [x] Remove giella-shared when everything has stabilized (incl. ensuring the full history of the content of the new repos is retained, cf [this task](https://github.com/orgs/giellalt/projects/3#card-82328396))

# Comments welcome!

@flammie and I discussed this today, the notes above are based on that. We would very much like feedback on these ideas from anyone, but especially from @TinoDidriksen @bbqsrc @Eijebong @Trondtr @aarppe

**Comment by snomos** [comment]
The only thing I would like to improve with the new shared repos is the date of the commits. They seem to now be from the date that @flammie did the split, and not from the actual date of the commit. Could that be fixed? Also, the history does not go all the way back to the start, but that could be a left-over thing from the svn-to-git conversion.

**Comment by flammie** [comment]
I used this: https://stackoverflow.com/questions/1365541/how-to-move-some-files-from-one-git-repo-to-another-not-a-clone-preserving-hi/11426261#11426261 to do the  history, the commit dates look right to me on command line git but github seems to have different timing, maybe the --commiter-date-is-author-date option was wrong? This method is also nice because you can basically sed the log for anomalies that break the thing like massive moves.

**Comment by snomos** [comment]
This is what it looks like in Tower, where the details reveal what is going wrong:

<img width="1033" alt="Skjermbilde 2022-05-24 kl  08 44 46" src="https://user-images.githubusercontent.com/1255285/169957932-ff3df574-7f0b-4377-8fe4-736ebb6d834d.png">

That is, I am the author (and @flammie the committer). Tower (and GitHub) uses the committer date, whereas the CLI log uses the author date. Ideally I would like committer = author (unless there is a real (PR) merge, which I don't think we've had so far for this repo or the parent repo).

Finally, we should also make sure that the history is complete. That is tracked in [a separate project](https://github.com/orgs/giellalt/projects/3).

**Comment by TinoDidriksen** [comment]
It's trivial to fix since the author info is there and correct, but it will mean a force push to the repos.

**Comment by snomos** [comment]
Done using this command for `shared-smi` (worked very well):

```sh
git filter-branch -f --commit-filter \           
   'export GIT_COMMITTER_NAME=\"$GIT_AUTHOR_NAME\";
    export GIT_COMMITTER_EMAIL=\"$GIT_AUTHOR_EMAIL\";
    export GIT_COMMITTER_DATE=\"$GIT_AUTHOR_DATE\";
    git commit-tree $@' \
    -- --all
```

and force-pushed. Will also do the other repos, and finally clean up some wrong emails. Ie more force-pushing coming up.

**Comment by snomos** [comment]
Just for reference, emails are cleaned using this command:

```sh
git filter-branch --env-filter 'if [ "$GIT_AUTHOR_EMAIL" = "incorrect@email" ]; then
     GIT_AUTHOR_EMAIL=correct@email;
     GIT_AUTHOR_NAME="Correct Name";
     GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL;
     GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"; fi' -- --all
```

taken from https://stackoverflow.com/questions/4981126/how-to-amend-several-commits-in-git-to-change-author.

**Comment by snomos** [comment]
After the above, I filtered `shared-mul` using `git filter-branch` to get rid of `src/filters/` (they are in `giella-core` now), and reordered one commit to get it into the correct order. Now all the dates are mangled again, but still with correct author date recorded. Only problem is, when I try to run the command above now, it ends with this error message:

```sh
Rewrite b5fcc6dba1a3915844f8641575bab14490229e5a (62/70) (3 seconds passed, remaining 0 predicted)    
Ref 'refs/heads/main' was deleted
fatal: Not a valid object name HEAD
zsh: command not found: export GIT_COMMITTER_NAME=\"$GIT_AUTHOR_NAME\";\n    export GIT_COMMITTER_EMAIL=\"$GIT_AUTHOR_EMAIL\";\n    export GIT_COMMITTER_DATE=\"$GIT_AUTHOR_DATE\";\n    git commit-tree $@
```

and the repo is busted. Of course one can live with wrong dates, it is just very irritating. Anyone any idea on how to fix the repo so that the dates are correct again?

**Comment by TinoDidriksen** [comment]
You somehow got 11 spaces after `git filter-branch -f --commit-filter \` so it was `git filter-branch -f --commit-filter \...........` (spaces shown as dots) and this ruined the paste. I've edited your comment to remove the spaces.

**Comment by snomos** [comment]
Thanks, that fixed it, and now `shared-mul` is done.

**Comment by snomos** [comment]
This is now all done. Dependency management can be refined, but it works across all CI/build systems, which is good enough.
