### ISSUE TITLE
SMI-specific paths in Giella-core/am-shared

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#21]
`am-shared/tools-mt-cgbased-dir-include.am` includes references to gt_SHARED_smi, which is no good. It should either be in `shared-mul`, or in `giella-core`, or be completely optional. Specifically, it relates to the [following lines of code](https://github.com/giellalt/giella-core/blob/068c55a7599eccb49baedf5acc1e7fc0873d2981/am-shared/tools-mt-cgbased-dir-include.am#L48-L56).

Viewpoints, @flammie @Trondtr @lynnda-hill @leneantonsen @TinoDidriksen ?

**Comment by snomos** [comment]
The same goes for [this file](https://github.com/giellalt/giella-core/blob/068c55a7599eccb49baedf5acc1e7fc0873d2981/am-shared/tools-mt-apertium-dir-include.am#L316-L324).

**Comment by flammie** [comment]
I didn't hear anything so I put gt_SHARED_smi snippets from core to specific langs for now, it mostly concerns builds with `--enable-apertium` so it shouldn't break too much also it would not have been working at all before for languages that did not have smi in configure.ac anyways.

**Comment by snomos** [comment]
Seems good. I'll close.
