### ISSUE TITLE
`specification` variable in `scripts/editdist.py:main` is unbound

### ISSUE THREAD

**Issue by Eijebong** [giellalt/giella-core#22]
See here:
https://github.com/giellalt/giella-core/blob/e0331988eaa3e6ed9640f5715c78385bcf8bfc17/scripts/editdist.py#L529

The specification variable is never assigned to in that function, eating the real error message as seen here: https://divvun-tc.giellalt.org/tasks/Tws-HWjpS_G2XXKN6BuLRw/runs/0/logs/public/logs/live.log#L8134

**Comment by snomos** [comment]
@albbas can you have a look? This is python 🙂

**Comment by albbas** [comment]
Will do
