### ISSUE TITLE
Bygging kræsjer i tools/grammarcheckers/filters

### ISSUE THREAD

**Issue by albbas** [giellalt/giella-core#33]
`./configure --enable-all-tools` fører til full stopp i byggingen med beskjeden

```
Making all in grammarcheckers
Making all in filters
make[3]: *** No rule to make target `.hfst', needed by `desktopspeller-sigma.txt'.  Stop.
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Det er samme problem i lang-sme og lang-sma

**Comment by albbas** [comment]
git bisect sier at 18f4b7a5ce39a6e4389565c79168038b5c94e5e8 er synderen.

Den innfører variabelen TAG_EXTRACTION_TTS_FST, og den er tom av en eller annen grunn.

**Comment by snomos** [comment]
aha - ja, no ser eg - eg fann ikkje ein måte å få til å fanga opp rett FST for å trekkja ut tagga på som fungerer både med TTS og med andre FST-ar.

Så utfordringa ligg i å gjera koden i den innsjekkinga betre og meir robust enn det eg klarte. @flammie kan du sjå på det?

**Comment by flammie** [comment]
en andra mulighet er å sette `TAG_EXTRACTION_FST` med `if WANT_TTS else endif` som kann vara litt mer robust

**Comment by albbas** [comment]
Nå blir filnavnet fanget opp, men kan ikke kompileres: 

```
make[2]: *** No rule to make target `analyser-tts-gt-output.hfst', needed by `analyser-tts-gt-output.hfstol'.  Stop.
```

**Comment by albbas** [comment]
Lukker denne, den opprinnelige grunnen til feilen er fikset.
