### ISSUE TITLE
Errors in AWK script converting in-source jspwiki to markdown

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#4]
The first test docs can be found in [lang-sma](/giellalt/lang-sma) - scroll to **Documentation** and click **In-source documentation**. The following things should be fixed:

- [x] tables
- [x] definition lists
- [x] nested lists
- [x] numbered lists
- [x] boldface in all cases

Add more bugs to the list above as they are found, and we can check them off as they get fixed.

**Comment by flammie** [comment]
tables can be a non-trivial problem, github probably requires a header row for all tables underlined, I noticed this is more lenient in jekyll which renders more broken tables.

| th1 | th2 |
|----|-----|
|  td1 | td2 |
| td3 | td4 |

works

| td1 | td2 |

does not?

**Comment by snomos** [comment]
Yes, it seems so. That is, we need to convert:

```
|| header || text
| table  | content
```

to:

```
| header | text
| --- | ---
| table  | content
```
with an equal number of `| --- ` sequences as the number of columns, and such that the top row is not reprocessed as a regular table line.

**Comment by snomos** [comment]
In cases where there is no header row, the only thing we can do is go and fix the source manually, IMHO. That will also make the table easier to read.

**Comment by snomos** [comment]
The present state of the table header conversion code is now as follows:

- it works partially, but the non-border ||'s are left as is, which is interpreted as an extra column, we thus need a way to change them into single bars
- the header separator row (required for gfmd table rendering) is hard-coded to two columns - I have no idea on how to make it dynamic using (G)AWK

If you can fix these two things, that would be a big YAY! @flammie

**Comment by snomos** [comment]
This seems to work as it should, and have been for a while. Closed
