### ISSUE TITLE
Relax dependency on `kbdgen` for mobile spellers

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#46]
Many/most CI/CD speller builds fail because it tries to build the keyboard layout error model using `kbdgen`, and it can't find the tool. Even if it could, it would not work, since keyboard layout error model generation is not yet reimplemented in the Rust version of `kbdgeb`.

We thus need to ensure that mobile spellers are built even when the keyboard layout error model file is not present, basically making the speller identical to the desktop speller.

**Comment by snomos** [comment]
Fails of the following type could be related:

```
make[3]: Entering directory '/root/tasks/E5bLeDVJScu5le6DOeDEBg/lang/build/tools/spellcheckers'
make[3]: *** No rule to make target 'errmodel.default.mobile.hfst', needed by 'kl-mobile.zhfst'.  Stop.
make[3]: Leaving directory '/root/tasks/E5bLeDVJScu5le6DOeDEBg/lang/build/tools/spellcheckers'
```

**Comment by flammie** [comment]
I commented out some `keyboardlayout.*` in shared make rules, it was named as a dependency in mobile keyboard build in one step but not used as far as I see.
