### ISSUE TITLE
mob_spellercorpus.unitweight.txt missing

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/giella-core#48]
Pristine `--enable-hfst-mobile-speller` builds die with `No rule to make target 'mob_spellercorpus.unitweight.txt', needed by '.generated/mob_unitweighted.hfst'.`

**Comment by flammie** [comment]
this runs fine on my linux:

```
$ history | tail
 3105  git clone git@github.com:giellalt/lang-kal vdwnopaw
 3106  cd vdwnopaw/
 3107  ./autogen.sh 
 3108  ./configure --enable-hfst-mobile-speller 
 3109  make
```

**Comment by TinoDidriksen** [comment]
Hm. Full line is `./configure --without-forrest --with-hfst --without-xfst --enable-reversed-intersect --enable-spellers --enable-hfst-mobile-speller --enable-hyperminimisation --enable-alignment --enable-minimised-spellers --enable-syntax --enable-analysers --enable-generators --enable-apertium --with-backend-format=foma --enable-dicts --enable-oahpa --enable-morpher --enable-tokenisers --disable-hfst-desktop-spellers`
