### ISSUE TITLE
Ampersand in the end of lexicon names breaks @CODE@ formatting

### ISSUE THREAD

**Issue by trondtynnol** [giellalt/giella-core#50]
A lang-kal developer has reported that when a lexicon name ends in `&`, and the line is included in documentation using `@CODE@`, the documentation is not generated correctly. E.g. in line 952 of [lang-kal/src/cg3/disambiguator.cg3](https://github.com/giellalt/lang-kal/blob/main/src/cg3/disambiguator.cg3) ([documentation page](https://giellalt.github.io/lang-kal/src-cg3-disambiguator.cg3.html)):
```
SET IVTVSUBJ& = IV_SUBJ& | SUBJTRANSVERB& ;  #!!≈ - **@CODE@**
````
This should be generated as
- **SET IVTVSUBJ& = IV_SUBJ& | SUBJTRANSVERB& ;**

but is instead generated as 
- \*\*SET IVTVSUBJ@CODE@ = IV_SUBJ@CODE@ | SUBJTRANSVERB@CODE@ ;\*\*

**Comment by flammie** [comment]
I guess all kinds of regex symbols might be problematic in code, should work nwo for the &
