### ISSUE TITLE
New languages errors out in CI due to missing files that are there

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#52]
Steps to reproduce

1. clone a newly added language, e.g. [lang-ceb](https://github.com/giellalt/lang-ceb)
2. `cd lang-ceb && ./autogen.sh && mkdir -p build/default/ && cd build/default/ && ../../configure && make -j`

Notice that it fails with the following error:

```
Making all in cg3
Making all in .
make[3]: *** No rule to make target `dependency.cg3', needed by `dependency.bin'.  Stop.
```

This is identical to CI build failures.

Notice the following:
- the file `dependency.cg3` exists in the source tree
- this only happens on a fresh clone (which is always the case in CI)

This bug is presently the only thing I am aware of preventing newly added languages from building cleanly.

**Comment by snomos** [comment]
I believe we should remove it from `.gitignore` - it can be ignored specifically for the languages that need it.

**Comment by flammie** [comment]
fixed in template and -ceb now, the languages that have shared-smi retain the old gitignores

**Comment by snomos** [comment]
> fixed in template and -ceb now, the languages that have shared-smi retain the old gitignores

Good 😊

Would it be better to move the exceptional ignore for the shared-smi languages to a subdir ignore, and keep the top level ignore file identical for all languages? That should make template updates less conflict prone.

**Comment by flammie** [comment]
> Would it be better to move the exceptional ignore for the shared-smi languages to a subdir ignore, and keep the top level ignore file identical for all languages? That should make template updates less conflict prone.

Sounds good
