### ISSUE TITLE
Spellers: no final strings and alt WS causes build error

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#53]
There's a bug in the Makefiles that causes the build to fail with an error similar to:

```
  GEN      .generated/editdist.Runr.regex
  HRGX2FST .generated/editdist.Runr.hfst
HUNION .generated/editdist.all.Runr.hfst
  HRGX2FST .generated/errmodel.Runr.hfst
*** xre parsing failed: Error reading transducer file '.generated/final_strings.all.Runr.hfst'.
/usr/local/bin/hfst-regexp2fst: <stdin>: XRE parsing failed in expression #1 separated by semicolons
/usr/local/bin/hfst-push-weights: <stdin> is not a valid transducer file
/usr/local/bin/hfst-fst2fst: <stdin> is not a valid transducer file
make[3]: *** [.generated/errmodel.Runr.hfst] Error 1
```

The bug is visible in `lang-nno` at [this revsion](https://github.com/giellalt/lang-nno/tree/134a78d142e2a478e29e306393dc89a7d82abab1).

To reproduce:
- start with a fresh clone
- use VPATH builds
- configure using `../../configure --enable-spellers`

In the case of `lang-nno`, the bug was worked around by adding final string error model files, and changing the Makefile setting for `FINAL_STRING_EDITS=` from `no` to `txt`.

The bug seems to be related to the logic for building the error model when the final string setting is different from `txt`, `regex` or `both`.

**Comment by flammie** [comment]
may be fixed in https://github.com/giellalt/giella-core/commit/a6e4cd66d02b88038190483368cd7d0a761aaba9
