### ISSUE TITLE
Emojis won't build

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#66]
To repeat:

- get a clean repo (`lang-tkl` tested)
- configure as `./configure --enable-spellers`
- `make V=1`

Output:

```sh
➜ cd src/fst/morphology
src/fst/morphology on  main 
➜ make V=1                        
Making all in .
cp -f /Users/smo036/langtech/gut/giellalt/lang-tkl/./../shared-mul/src/fst/emojis.lexc .generated/emojis.tmp.lexc
"/usr/local/bin/hfst-lexc" \
		-v --format=foma --Werror   --alignStrings -o .generated/.generated/emojis.tmp.hfst .generated/emojis.tmp.lexc
/usr/local/bin/hfst-lexc: Could not open '.generated/.generated/emojis.tmp.hfst'. No such file or directory
make[1]: *** [.generated/.generated/emojis.tmp.hfst] Error 1
rm .generated/emojis.tmp.lexc
make: *** [all-recursive] Error 1
```

The problem is the double `.generated` in `.generated/.generated/emojis.tmp.hfst`. I have not been able to figure out why, and how to solve it.

**Comment by flammie** [comment]
This is the same issue as with url's as it shares the make scripts, it only shows up on Macs and is previously documented here: https://github.com/giellalt/template-lang-und/issues/8#issuecomment-1903684405

I commented out some copying rule in giella-core that might help?

**Comment by snomos** [comment]
The strang thing is that `url.lexc` etc compiles without issues for me, whereas `emojis.lexc` does not, although they should be exactly identical. I don't get it.

**Comment by TinoDidriksen** [comment]
Seems to work now. Everything builds on my Mac, even after `git clean -f -d -x` in all folders.

**Comment by flammie** [comment]
cool I'll close

**Comment by TinoDidriksen** [comment]
Oops, nevermind. Got this rather different error that I missed in the logs:
```
Making all in transcriptions
make[3]: *** No rule to make target `transcriptor-clock-digit2text.filtered.lookup.hfstol', needed by `all-am'.  Stop.
```

**Comment by flammie** [comment]
ah yes, of course there are some other things depending on lexc compilation that I didn't think of, 
I've let single lexc's to be copied around to .gen for now, hopefully it doesn't bring back some other mac only problem with wildcards and matching

**Comment by TinoDidriksen** [comment]
That fixed it. This time for real.

**Comment by jeutzsch** [comment]
sje (Pite Saami) still returns an error upon `make`
`make[4]: *** No rule to make target '.generated/emojis.hfst', needed by 'all-am'.  Stop.`
`make[3]: *** [all-recursive] Error 1`
`make[2]: *** [all-recursive] Error 1`
`make[1]: *** [all-recursive] Error 1`
`make: *** [all-recursive] Error 1`
(I assume this is related, but I'm not sure...)

**Comment by TinoDidriksen** [comment]
`sje` builds for me - you probably don't have latest dependencies.

**Comment by jeutzsch** [comment]
> `sje` builds for me - you probably don't have latest dependencies.

I did `git pull` for sje and giella-core (obviously) and also ran `install-nightly.sh` – what else could it be?

**Comment by snomos** [comment]
git pull `shared-mul` :)

**Comment by jeutzsch** [comment]
thanks, @snomos! `shared-mul` is not part of my regular git-pull, but I will add it!
